<?php

namespace Paladin\Enum;

use MyCLabs\Enum\Enum;

class LoggerEnum extends Enum
{
    const SEND_EMAIL_FAILED = "SEND_EMAIL_FAILED";
    const LOGIN_FAILED = "LOGIN_FAILED";
    const LOGIN_WITHOUT_PASSWORD_FAILED = "LOGIN_WITHOUT_PASSWORD_FAILED";
    const AUTHORIZATION_TOKEN_CREATE_FAILED = "AUTHORIZATION_TOKEN_CREATE_FAILED";
    const ACTIVATE_USER_FAILED = "ACTIVATE_USER_FAILED";
    const CREATE_USER_FAILED = "CREATE_USER_FAILED";
}
