<?php

// Environment
define("ACCESS_CONTROL_ALLOW_CREDENTIALS", $_ENV["ACCESS_CONTROL_ALLOW_CREDENTIALS"]);
define("ACCESS_CONTROL_ALLOW_HEADERS", $_ENV["ACCESS_CONTROL_ALLOW_HEADERS"]);
define("ACCESS_CONTROL_EXPOSE_HEADERS", $_ENV["ACCESS_CONTROL_EXPOSE_HEADERS"]);
define("ADMIN_EMAIL", $_ENV["ADMIN_EMAIL"]);
define("CLIENT_PROTOCOL", $_ENV["CLIENT_PROTOCOL"]);
define("CLIENT_DOMAIN", $_ENV["CLIENT_DOMAIN"]);
define("DEBUG_LOG", $_ENV["DEBUG_LOG"]);
define("DEFAULT_LOCALE", $_ENV["DEFAULT_LOCALE"]); // Must be present in SUPPORTED_LOCALES
define("ENVIRONMENT", $_ENV["ENVIRONMENT"]);
define("ERROR_REPORTING", $_ENV["ERROR_REPORTING"]);
define("FORCE_HTTPS", $_ENV["FORCE_HTTPS"]);
define("INFO_EMAIL", $_ENV["INFO_EMAIL"]);
define("MAILER_HOST", $_ENV["MAILER_HOST"]);
define("MAILER_PORT", $_ENV["MAILER_PORT"]);
define("MAILER_USER", $_ENV["MAILER_USER"]);
define("MAILER_PASSWORD", $_ENV["MAILER_PASSWORD"]);
define("MONGO_INITDB_DATABASE", $_ENV["MONGO_INITDB_DATABASE"]);
define("MONGO_PASSWORD_FILE", $_ENV["MONGO_PASSWORD_FILE"]);
define("MONGO_PORT", $_ENV["MONGO_PORT"]);
define("MONGO_HOST", $_ENV["MONGO_HOST"]);
define("MONGO_USER", $_ENV["MONGO_USER"]);
define("SITE_NAME", $_ENV["SITE_NAME"]);
define("REDIS_HOST", $_ENV["REDIS_HOST"]);
define("REDIS_PORT", $_ENV["REDIS_PORT"]);

// Derived
const CLIENT_URL = CLIENT_PROTOCOL . CLIENT_DOMAIN;

// Other
const DS = DIRECTORY_SEPARATOR;
const SUPPORTED_LOCALES = ["cs_CZ", "en_US"];
